### PR TITLE
Update events.go to read the Facebook token from .env

### PR DESCRIPTION
**Pull request by abiramen**
# Change

Facebook tokens are now read from a Docker environment variable rather than constants.go.

## Change reason

Passing environment variables was the chosen method for safely storing secrets, with a gitignored .env file being shared between developers.  This prevents leakage of the Facebook token due to accidental commits, which is imperative due to the wide array of privileges associated with it.

### CODE REVIEW

**Comment by abiramen** [comment]
Hmm, I'm stumped with the failed check there.

**Comment by glebme** [comment]
Failed check is the JWT. If you do a pull/rebase from master should be fixed.

On a different note how does one get access to this .env file. As well as @sergiomercado19 if your .env file includes the mailing one.

**Review by glebme — COMMENTED** [review]
Refer to previous comment.

**Review by gawdn — APPROVED** [review]
LGTM after checks pass

**Comment by sergiomercado19** [comment]
> Failed check is the JWT. If you do a pull/rebase from master should be fixed.
> 
> On a different note how does one get access to this .env file. As well as @sergiomercado19 if your .env file includes the mailing one.

@glebme Mine .env file has the Mailjet token, yes. I think we should ensure that everyone has the same `.env` file by sharing it through more secure means.

**Pull request merged**
