### PR TITLE
CW-162 Slideshow component

### PR DESCRIPTION
**Pull request by sergiomercado19**
## Changes
- Created an _InfiniteSlideshow_ component that takes in: duration, delay, direction and paused. These all correspond to animation-related CSS properties.
- Added the InfiniteSlideshow component to the landing page to display event banners.

## Change reason
This addition is part of our attempt at implementing the wireframes.

## Comments
InfiniteSlideshow uses the concept of _slots_ which essentially enable components to take in data in the form of JSX children elements. The <slot> tag then serves as a placeholder to where theses elements will go. In this instance, slots are used to pass in multiple img to cycle through in the slideshow.

I haven't added the slideshow to the menu because animations apparently use a fair bit of resources, noticeable on less powerful devices.

### CODE REVIEW

**Comment by glebme** [comment]
Another comment that isn't apart of my review: Is there an option for a click and drag part to replace the automatic nature of the slideshow? This is just to get the user later on to interact with the website instead of mindlessly scrolling. Something to consider when working towards deployment.

**Comment by sergiomercado19** [comment]
> One thing is that I think the sliding is a bit too fast. I feel like I'm about to have an epileptic episode.

Hehe, well lucky for you @glebme the InfitySlideshow component takes in a prop called duration. The higher the value the slower it goes. You play around and tell me what the optimal duration is.

`<InfinitySlideshow duration='15s'>`

Note the 's' in the duration prop is needed as this is passed directly to a CSS animation property.

**Comment by glebme** [comment]
I think regardless of the speed i put it at it still gives me a dizzy feeling. I set it at 120 which seems like a good medium but @paulatennent give us your thoughts.

**Comment by paulatennent** [comment]
OMG THIS LOOKS SO GOOD, But i agree that its still too fast, and because the middle on is going in the opposite direction, it seems like its going twice as fast so we could set it to 30, 40, 30. Also, i messed around with it and found that these settings were pretty sleek and didnt make me feel dizzy
`duration="32s" direction="reverse"`
`duration="35s" direction="reverse"`
`duration="30s" direction="reverse"`
(i have a video if you dont want to docker up again)

**Comment by sergiomercado19** [comment]
I already had docker up hehe. I've fixed up the speed. Can you guys approve if it looks good please 😃

**Comment by glebme** [comment]
On closer inspection I think it had to do with too many slide shows. If i reduce it to two and @ least double the time then it seems ok, im worried for those who have motion sickness because this will get them definitely. Also on smaller screens i think 2 fits the window length well not sure about bigger screens.

**Pull request merged**
