### PR TITLE
CW-201 Cypress Testing

### PR DESCRIPTION
**Pull request by glebme**
# Change

_Allow for cypress testing in github actions._

## Change reason

Necessary progression in using Github actions as our CI. #97

### CODE REVIEW

**Comment by glebme** [comment]
Added checks are failing because cypress has failed which at least we know its working.

**Review by sergiomercado19 — CHANGES_REQUESTED** [review]
Look good! Can you just change the name of the job in line 15, since it's not just backend testing anymore. I looked into shared shared steps (docker composing) between Github Actions jobs to separate frontend and backend testing but didn't find anything.

Also, as you suggested, remove the Preview test that is failing since that component will be made redundant soon.

**Comment by glebme** [comment]
> Looks good! Can you just change the name of the job in line 15, since it's not just backend testing anymore. I looked into shared shared steps (docker composing) between Github Actions jobs to separate frontend and backend testing but didn't find anything.
> 
> Also, as you suggested, remove the Preview test that is failing since that component will be made redundant soon.

Will do.

**Review by sergiomercado19 — APPROVED** [review]
Looks good, go ahead and merge.

**Pull request merged**
