### PR TITLE
CW-247 Fix event display on homepage

### PR DESCRIPTION
**Pull request by abiramen**
# Change

Update event dummy data to have valid images, and scale image sizes to match heights.

## Change reason

- As some developers are currently using dummy data for events, the data had to be updated to display images with valid URL signatures (FB image URLs seem to last about 30 days)
- Images of different aspect ratios displayed with varying heights - this has now been fixed.

### CODE REVIEW

**Comment by glebme** [comment]
Images are still not loading for me. But as seeing this is still the case, shall we begin the pivot to make it live fetches? Can you figure out a way to distribute safely the token and report back to us?

**Review by glebme — CHANGES_REQUESTED** [review]
As per above.

**Comment by glebme** [comment]
@abiramen any movement on this?

**Comment by abiramen** [comment]
Should be resolved by everyone having valid tokens, although I'll need to push a change so that events are actively being fetched.

**Comment by glebme** [comment]
> Should be resolved by everyone having valid tokens, although I'll need to push a change so that events are actively being fetched.

Since i now have the token we're good to push because I can share with people as a i debug their problems.

**Pull request merged**
