### PR TITLE
CW-234 Reponsive Landing Page

### PR DESCRIPTION
**Pull request by glebme**
# Change

_Responsive design for lower screen resolutions._

## Change reason

At lower screen resolutions/viewports, the website design and implementation was not handled. These changes begin to address some of the responsive issues we had especially text size, background images and information layout. To avoid having to retroactively apply design and code in a way that is screen size agnostic or in a way with smaller screen sizes in consideration.

## Comments

- The main point of opening this PR is to elicit feedback and to see what other areas need to be addressed besides the ones mentioned above and below.
- At this point this is we're ready to go.
- Spacing has not been taken into consideration and is also another thing to change to align cohesiveness of the website at smaller screen sizes.
- Menu nor footer has been touched but are areas of 'responsive' concern.

### CODE REVIEW

**Review by sergiomercado19 — APPROVED** [review]
Looks good!

**Review by abiramen — APPROVED** [review]
Looks good to me.

**Comment by JarvisWang0715** [comment]
We might need to change the font size of the heading when switching to mobile screen and the spacing for the sponsor us area seems a bit off for me.

**Review by JarvisWang0715 — APPROVED** [review]

**Review by sergiomercado19 — APPROVED** [review]
Looks good to me! My only qualm is the community links not opening on another tab.

**Pull request merged**
