### PR TITLE
CW-154 Menu component

### PR DESCRIPTION
**Pull request by sergiomercado19**
## Changes
- Changed the menu from a sidebar to an overlay.

## Change reason
I changed this to comply with the wireframe.

## Comments
Replaced the _Sidebar_ view with the _Menu_ view.
NOTE: This PR doesn't include the gallery slideshow behind the menu.

### CODE REVIEW

**Comment by sergiomercado19** [comment]
Disabling hover on touch devices seems a bit outside the scope of this PR, as shown [here](https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices). I reckon we will have to redesign the website for mobile anyway, and use some magic to figure out which version of the page gets rendered. We will just have to ensure that the mobile version doesn't have any `:hover` in CSS.

**Comment by sergiomercado19** [comment]
Disabling hover on touch devices seems a bit outside the scope of this PR, as shown [here](https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices). I reckon we will have to redesign the website for mobile anyway, and use some magic to figure out which version of the page gets rendered, depending on the device. We will just have to ensure that the mobile version doesn't have any `:hover` in CSS.

**Comment by paulatennent** [comment]
- screen size looks good on my tiny ass screen
- it doesnt seem natural for it to enlarge when on the background no where near the words, could we make it so it only get bigger when the cursor is on or near the words?
- can we make it so you can exit by clicking on the background.
- clicking on csesoc_ when on the menu page should make the menu go away (when on another page and the menu is open, clicking on csesoc logo brings you to the front page with the menu open)
- (sort of unrelated: but the tab logo is still hackathon logo, it might be something to do with my yarn install cache tho idk reall how yarn works)

**Comment by paulatennent** [comment]
also i think the order should be changed, maybe 'about, events, cse resources, sponsors, shop, engage', just make sure that shop is not second and engage us usually last

**Comment by sergiomercado19** [comment]
Awesome feedback guys 🎉

@glebme a couple clarifications are needed:

> doesn't look like the back is blacked out any more

It was always at 90% transparency to black, should I make it fully black?

> you can also scroll and it will scroll the background

I know... if I lock scrolling the scrollbar disappears and cause the page to resize slightly, which was kinda bothering me hehe. Should I lock scrolling?

@paulatennent some comments for you:

> it doesnt seem natural for it to bold when on the background no where near the words, could we make it so it only get bigger when the cursor is on or near the words?

With this I'll have to find a balance, because if the width of the box containing the text is not wide enough (meaning a smaller clicking area) the text will wrap around. This was specially noticeable in "CSE Resources"

> also i think the order should be changed, maybe 'about, events, cse resources, sponsors, shop, engage', just make sure that shop is not second and engage us usually last

I went off by what was on the wireframe in Adobe XD, change it over there and I'll re-order it here

**Comment by sergiomercado19** [comment]
> (sort of unrelated: but the tab logo is still hackathon logo, it might be something to do with my yarn install cache tho idk reall how yarn works)

@paulatennent open your dev tools and do a "Empty Cache and Hard Reload" by right clicking on the reload icon. This happened because the Momentum website was running on the same port hehe 
image

**Comment by glebme** [comment]
@sergiomercado19 MY SCREENSHOT CHANGED I SWEAR THE OPACITY WAS LIKE 30% AND I COULD CLEARLY SEE THE BACKGROUND. Maybe its my lack of sleep.

On the second point wouldn't matter if the opacity was black and you unlock scrolling after you leave the nav?

**Comment by sergiomercado19** [comment]
> On the second point wouldn't matter if the opacity was black and you unlock scrolling after you leave the nav?

Yep, if it was fully black then the scroll-locking (and slight resizing) wouldn't matter. I'll go ahead and change that 😃
All this will be irrelevant once I do the slideshow behind the menu anyway.

**Comment by glebme** [comment]
Forgot to say to link the sponsors page that Jie's doing atm.

**Comment by sergiomercado19** [comment]
The flex-box takes care of that, I'd have to centre it manually to fix that 😬
```
  display: flex;
  flex-direction: column;
  justify-content: center;
```

**Comment by paulatennent** [comment]
i dont think opening and closing the menu should take you back up to the top of the page, other then that looks all good now

**Comment by glebme** [comment]
> i dont think opening and closing the menu should take you back up to the top of the page, looks good tho!

oh i didnt happen to see this when i was testing but i pull back my approval for this

**Comment by sergiomercado19** [comment]
This bug was introduced by disabling scrolling. I've 'fixed it' by not disabling scrolling when the menu is open.

Normally this would be worked around by saving the y-position (and setting it after) when the menu is open using JS and the window.scrollTo(). I ended up realising that in Vue `window` is not in scope (outside mount and unmount). I also tried using a package called _vue-scrollto_ but it only supported scrolling to elements rather than a fixed position from the top of the page.

After looking at this for 2 hours, this is the best I can do 😬 without having to refactor the layout of the page around the `RouterView`.

**Pull request merged**
